# Generated by Django 2.0.2 on 2018-09-03 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv', models.BooleanField()),
                ('phone_no', models.CharField(max_length=15)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('cab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_no', models.CharField(max_length=30)),
                ('driver_name', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rating', models.IntegerField()),
                ('total_dist', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='daily_dist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trips',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('source_latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('source_longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('dest_latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('dest_longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('distance', models.IntegerField()),
                ('no_of_pass', models.IntegerField()),
                ('cab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsproj.Cab')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=15)),
                ('type', models.TextField(max_length=15)),
                ('no_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='voice_commands',
            fields=[
                ('voice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('voice_string', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cab',
            name='daily_dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsproj.daily_dist'),
        ),
        migrations.AddField(
            model_name='cab',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsproj.type'),
        ),
        migrations.AddField(
            model_name='cab',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsproj.AppUsers'),
        ),
    ]
