# Generated by Django 2.0.2 on 2018-09-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_dist',
            name='date',
            field=models.DateField(),
        ),
    ]
