# Generated by Django 2.0.2 on 2018-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsproj', '0002_auto_20180904_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_dist',
            name='distance',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
