# Generated by Django 2.0.2 on 2018-09-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsproj', '0005_auto_20180904_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cab',
            name='daily_dist',
        ),
        migrations.AddField(
            model_name='daily_dist',
            name='cab_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbmsproj.Cab'),
            preserve_default=False,
        ),
    ]
